[package]
name = "rustesp32"
version = "0.1.0"
authors = []
edition = "2018"
readme = "README.md"

[dependencies]
cty = "0.2"
esp_idf = "0.1"
esp-idf-sys = "0.1"

[build-dependencies]
glob = "0.3"
esp_idf_build = "0.1"
